### ISSUE TITLE
Make page title show function of that page/layout in workflow

### ISSUE THREAD

**Issue by dgroos** [602p/mps-punctuality#7]
For the landing/search page, change the title from "MPS Punctuality Tracker" to: "Find a Student"

Perhaps the way you have the layout of the admin tools page where "MPS Punctuality" is in the upper left corner and LOG OUT in the upper right would be a great way to standardize all pages, but could you call our installation, "South Punctuality Tracker"?

**Comment by 602p** [comment]
I've set up the navbar part. WIll do the title change soonish.
